
FROM python:2.7-slim

WORKDIR /app
ADD data_input.py /app/data_input.py
ADD requirements.txt /app/requirements.txt
VOLUME /data

RUN pip install -r requirements.txt
RUN ls -lsa /app

#ENV TARGET="localhost:9200"
ENTRYPOINT whoami; python /app/data_input.py

CMD /bin/bash
